import type { Trip } from "../Helper/ApiResponseInterface";
export const Data_Dummy: Trip = {
  id: "trip_1758447908",
  source: "Chikkamagaluru, Karnataka",
  destination: "Jaipur, Rajasthan",
  start_date: "2025-10-02",
  end_date: "2025-10-06",
  duration_days: 5,
  traveler_count: 2,
  travel_style: "luxury",
  budget: 100000,
  saved: 11600,
  total_cost: 88400,
  cost_per_person: 44200,
  budget_breakdown: {
    accommodation: 35000,
    transport: 30000,
    activities: 15000,
    meals: 7000,
    miscellaneous: 1400,
  },
  day_plans: [
    {
      day_number: 1,
      date: "2025-10-02",
      title: "Arrival in Jaipur \u0026 Royal Welcome",
      description:
        "Arrive in Jaipur, the Pink City, and check into your luxurious heritage resort. Spend the afternoon relaxing and acclimatizing, followed by an evening exploring local culture and cuisine.",
      activities: [
        {
          id: "ACT001",
          name: "Arrival and Check-in",
          description:
            "Arrive at Jaipur Airport (JAI) and take a pre-booked luxury car to your resort. Check in and relax.",
          category: "Transport",
          type: "Flight + Car",
          location: {
            name: "Jaipur International Airport",
            address:
              "Affluent Colony, Sanganer, Jaipur, Rajasthan 303011, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.827643,
            longitude: 75.812073,
          },
          start_time: "10:00",
          end_time: "12:00",
          duration: "2 hours",
          cost: 5000,
          cost_per_person: 2500,
          booking_required: true,
          rating: 0,
          review_count: 0,
          tips: [
            "Book your flight from the nearest airport to Chikkamagaluru to Jaipur in advance.",
            "Arrange for airport pickup with your hotel or a private car service.",
          ],
          priority: 1,
        },
        {
          id: "ACT002",
          name: "Relaxation and Resort Exploration",
          description:
            "Unwind at your resort. Enjoy the amenities, perhaps a spa treatment or a leisurely walk through the gardens.",
          category: "Wellness",
          type: "Leisure",
          location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          start_time: "12:00",
          end_time: "17:00",
          duration: "5 hours",
          cost: 0,
          cost_per_person: 0,
          booking_required: false,
          rating: 4.5,
          review_count: 5000,
          tips: [
            "Consider booking a spa session in advance.",
            "Enjoy the heritage architecture of the palace.",
          ],
          priority: 2,
        },
        {
          id: "ACT003",
          name: "Evening Cultural Immersion \u0026 Dinner",
          description:
            "Experience the vibrant culture of Jaipur with a traditional Rajasthani folk music and dance performance, followed by a delightful vegetarian dinner.",
          category: "Culture",
          type: "Performance \u0026 Dining",
          location: {
            name: "Local Cultural Village/Resort Venue",
            address: "Various locations in Jaipur",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912427,
            longitude: 75.787473,
          },
          start_time: "18:00",
          end_time: "21:00",
          duration: "3 hours",
          cost: 6000,
          cost_per_person: 3000,
          booking_required: true,
          rating: 4.2,
          review_count: 800,
          tips: [
            "Confirm the venue and timings with your resort.",
            "Engage with local artists and learn about their craft.",
          ],
          priority: 3,
        },
      ],
      meals: [
        {
          id: "MEAL001",
          type: "Dinner",
          restaurant_name: "Suvarna Mahal",
          description:
            "Indulge in authentic Rajasthani vegetarian delicacies at Suvarna Mahal, known for its royal ambiance and exquisite flavors.",
          cuisine: "Rajasthani, Indian",
          location: {
            name: "Suvarna Mahal",
            address:
              "RAMBAGH PALACE, Bhawani Singh Rd, Rambagh, Jaipur, Rajasthan 302015, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.898131,
            longitude: 75.80824,
          },
          reservation_time: "21:00",
          cost: 5000,
          cost_per_person: 2500,
          rating: 4.6,
          review_count: 1500,
          specialties: [
            "Dal Baati Churma",
            "Laal Maas (Vegetarian version available)",
            "Gatte ki Sabzi",
          ],
          dietary_info: [
            "Vegetarian",
            "Can accommodate specific dietary needs",
          ],
          booking_required: true,
        },
      ],
      transport: [
        {
          id: "TRN001",
          mode: "Luxury Car",
          from_location: {
            name: "Jaipur International Airport",
            address:
              "Affluent Colony, Sanganer, Jaipur, Rajasthan 303011, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.827643,
            longitude: 75.812073,
          },
          to_location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          departure_time: "10:00",
          arrival_time: "11:00",
          duration: "1 hour",
          cost: 2000,
          cost_per_person: 1000,
          description: "Airport transfer to the hotel.",
          notes: ["Ensure the car is air-conditioned for comfort."],
        },
      ],
      daily_cost: 13000,
      weather: {
        date: "2025-10-02",
        min_temp: 22,
        max_temp: 34,
        condition: "Sunny",
        description: "Pleasant day with clear skies.",
        humidity: 50,
        precipitation: 0,
        recommendation: "Light cotton clothing is suitable. Stay hydrated.",
      },
      notes: [
        "The journey from Chikkamagaluru to Jaipur will be via flight. This itinerary assumes arrival in Jaipur on Day 1.",
      ],
    },
    {
      day_number: 2,
      date: "2025-10-03",
      title: "Jaipur's Royal Heritage and Pink City Exploration",
      description:
        "Immerse yourself in the grandeur of Jaipur's iconic landmarks, from the majestic City Palace to the unique Hawa Mahal. Enjoy local flavors and vibrant markets.",
      activities: [
        {
          id: "ACT004",
          name: "City Palace Exploration",
          description:
            "Explore the magnificent City Palace complex, a blend of Rajasthani and Mughal architecture, housing museums and courtyards.",
          category: "History",
          type: "Heritage Site",
          location: {
            name: "The City Palace",
            address:
              "Gangori Bazaar, J.D.A. Market, Kanwar Nagar, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.925794,
            longitude: 75.823671,
          },
          start_time: "09:30",
          end_time: "12:30",
          duration: "3 hours",
          cost: 1000,
          cost_per_person: 500,
          booking_required: false,
          rating: 4.5,
          review_count: 15000,
          tips: [
            "Hire a local guide for a deeper understanding of the history.",
            "Wear comfortable shoes as you'll be doing a lot of walking.",
          ],
          opening_hours: "09:30 - 17:00",
          priority: 1,
        },
        {
          id: "ACT005",
          name: "Hawa Mahal Visit",
          description:
            "Marvel at the iconic Hawa Mahal (Palace of Winds), a stunning five-story facade with numerous small windows, designed for royal ladies to observe street life.",
          category: "History",
          type: "Iconic Landmark",
          location: {
            name: "Hawa Mahal",
            address:
              "Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Kanwar Nagar, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.924046,
            longitude: 75.826714,
          },
          start_time: "12:30",
          end_time: "13:30",
          duration: "1 hour",
          cost: 500,
          cost_per_person: 250,
          booking_required: false,
          rating: 4.4,
          review_count: 18000,
          tips: [
            "Best viewed from the outside for photography.",
            "Can be crowded, visit early if possible.",
          ],
          opening_hours: "09:00 - 17:00",
          priority: 2,
        },
        {
          id: "ACT006",
          name: "Bapu Bazaar Shopping",
          description:
            "Explore the bustling Bapu Bazaar, famous for its colorful textiles, handicrafts, jewelry, and traditional Rajasthani attire.",
          category: "Shopping",
          type: "Local Market",
          location: {
            name: "Bapu Bazaar",
            address: "Johari Bazaar Rd, Jaipur, Rajasthan 302003, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.9163,
            longitude: 75.8153,
          },
          start_time: "14:30",
          end_time: "17:00",
          duration: "2.5 hours",
          cost: 0,
          cost_per_person: 0,
          booking_required: false,
          rating: 4.3,
          review_count: 6000,
          tips: [
            "Bargaining is expected, start by offering 50-60% of the quoted price.",
            "Look for authentic block-printed fabrics and mojari (leather footwear).",
          ],
          opening_hours: "11:00 - 21:00",
          priority: 3,
        },
      ],
      meals: [
        {
          id: "MEAL002",
          type: "Lunch",
          restaurant_name: "Govindam Retreat",
          description:
            "Enjoy a wholesome and delicious vegetarian thali at Govindam Retreat, a popular spot near the Govind Dev Ji Temple.",
          cuisine: "Indian, Vegetarian",
          location: {
            name: "Govindam Retreat",
            address:
              "Brahampuri, First Floor, All Rajasthan Shilp Gram Udyog, Rajamal Ka Talab Rd, near Govind Dev Ji Temple, above All Rajasthan Shilp Gram Udyog, Gangori Bazaar, J.D.A. Market, Kanwar Nagar, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.928917,
            longitude: 75.825443,
          },
          reservation_time: "13:30",
          cost: 1200,
          cost_per_person: 600,
          rating: 4.3,
          review_count: 2500,
          specialties: ["Thali", "Paneer Dishes"],
          dietary_info: ["Vegetarian", "Pure Veg"],
          booking_required: false,
        },
      ],
      transport: [
        {
          id: "TRN002",
          mode: "Luxury Car",
          from_location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          to_location: {
            name: "The City Palace",
            address:
              "Gangori Bazaar, J.D.A. Market, Kanwar Nagar, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.925794,
            longitude: 75.823671,
          },
          departure_time: "09:30",
          arrival_time: "09:45",
          duration: "15 minutes",
          cost: 500,
          cost_per_person: 250,
          description: "Transfer to City Palace.",
          notes: ["Traffic can be heavy, allow for buffer time."],
        },
        {
          id: "TRN003",
          mode: "Luxury Car",
          from_location: {
            name: "The City Palace",
            address:
              "Gangori Bazaar, J.D.A. Market, Kanwar Nagar, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.925794,
            longitude: 75.823671,
          },
          to_location: {
            name: "Hawa Mahal",
            address:
              "Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Kanwar Nagar, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.924046,
            longitude: 75.826714,
          },
          departure_time: "12:30",
          arrival_time: "12:40",
          duration: "10 minutes",
          cost: 300,
          cost_per_person: 150,
          description: "Short transfer to Hawa Mahal.",
        },
        {
          id: "TRN004",
          mode: "Luxury Car",
          from_location: {
            name: "Hawa Mahal",
            address:
              "Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Kanwar Nagar, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.924046,
            longitude: 75.826714,
          },
          to_location: {
            name: "Bapu Bazaar",
            address: "Johari Bazaar Rd, Jaipur, Rajasthan 302003, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.9163,
            longitude: 75.8153,
          },
          departure_time: "13:30",
          arrival_time: "13:45",
          duration: "15 minutes",
          cost: 300,
          cost_per_person: 150,
          description: "Transfer to Bapu Bazaar for lunch and shopping.",
        },
        {
          id: "TRN005",
          mode: "Luxury Car",
          from_location: {
            name: "Bapu Bazaar",
            address: "Johari Bazaar Rd, Jaipur, Rajasthan 302003, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.9163,
            longitude: 75.8153,
          },
          to_location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          departure_time: "17:00",
          arrival_time: "17:15",
          duration: "15 minutes",
          cost: 500,
          cost_per_person: 250,
          description: "Return to the resort.",
        },
      ],
      daily_cost: 8100,
      weather: {
        date: "2025-10-03",
        min_temp: 23,
        max_temp: 35,
        condition: "Sunny",
        description: "Warm and pleasant day, ideal for sightseeing.",
        humidity: 45,
        precipitation: 0,
        recommendation:
          "Wear light, breathable clothing. Carry sunscreen and a hat.",
      },
    },
    {
      day_number: 3,
      date: "2025-10-04",
      title: "Amber Fort, Jal Mahal Serenity \u0026 Evening Delights",
      description:
        "Journey to the majestic Amber Fort, enjoy the serene beauty of Jal Mahal, and end the day with a lively evening at a rooftop bar.",
      activities: [
        {
          id: "ACT007",
          name: "Amber Fort Excursion",
          description:
            "Visit the stunning Amber Fort, a UNESCO World Heritage site, known for its artistic Hindu style, blend of Mughal architecture, and intricate carvings. Consider an elephant ride or jeep safari up to the fort.",
          category: "History",
          type: "Fortress",
          location: {
            name: "Amber Fort",
            address: "Deonta Amer, Amer, Jaipur, Rajasthan 302001, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 27.007657,
            longitude: 75.851549,
          },
          start_time: "09:00",
          end_time: "12:00",
          duration: "3 hours",
          cost: 1500,
          cost_per_person: 750,
          booking_required: false,
          rating: 4.6,
          review_count: 25000,
          tips: [
            "Arrive early to avoid crowds and the heat.",
            "Opt for a jeep ride if you prefer not to use the elephant safari.",
            "The sound and light show in the evening is also recommended, but check timings.",
          ],
          opening_hours: "08:00 - 17:30",
          priority: 1,
        },
        {
          id: "ACT008",
          name: "Jal Mahal Visit",
          description:
            "Admire the picturesque Jal Mahal (Water Palace), a stunning architectural marvel situated in the Man Sagar Lake. Enjoy the serene views.",
          category: "Scenic",
          type: "Palace",
          location: {
            name: "Jal Mahal",
            address: "Jal Mahal, Amer, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.953458,
            longitude: 75.846123,
          },
          start_time: "12:30",
          end_time: "13:00",
          duration: "30 minutes",
          cost: 0,
          cost_per_person: 0,
          booking_required: false,
          rating: 4.3,
          review_count: 12000,
          tips: [
            "The palace is usually viewed from the outside.",
            "Best time to visit for photography is during the golden hours.",
          ],
          priority: 2,
        },
        {
          id: "ACT009",
          name: "Evening Rooftop Experience",
          description:
            "Enjoy a lively evening with music, drinks, and panoramic city views at a popular rooftop bar.",
          category: "Nightlife",
          type: "Bar",
          location: {
            name: "Brewlicious Rooftop Bar Restaurant",
            address:
              "5, 10th floor, Gadi, Okay Plus Tower, Ajmer Rd, near kalyan jewellers, Hathroi, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.917089,
            longitude: 75.799779,
          },
          start_time: "19:30",
          end_time: "22:00",
          duration: "2.5 hours",
          cost: 7000,
          cost_per_person: 3500,
          booking_required: true,
          rating: 4.1,
          review_count: 3000,
          tips: [
            "Make a reservation in advance, especially on weekends.",
            "Enjoy the local craft beers if available.",
          ],
          opening_hours: "17:00 - 01:00",
          priority: 4,
        },
      ],
      meals: [
        {
          id: "MEAL003",
          type: "Lunch",
          restaurant_name: "Local Restaurant near Amber Fort",
          description:
            "Enjoy a traditional vegetarian Rajasthani lunch at a well-regarded local eatery near Amber Fort.",
          cuisine: "Rajasthani, Indian",
          location: {
            name: "Local Eatery",
            address: "Near Amber Fort, Jaipur",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 27.007657,
            longitude: 75.851549,
          },
          reservation_time: "13:00",
          cost: 1500,
          cost_per_person: 750,
          rating: 4,
          review_count: 500,
          specialties: ["Ker Sangri", "Pyaaz Kachori"],
          dietary_info: ["Vegetarian"],
          booking_required: false,
        },
      ],
      transport: [
        {
          id: "TRN006",
          mode: "Luxury Car",
          from_location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          to_location: {
            name: "Amber Fort",
            address: "Deonta Amer, Amer, Jaipur, Rajasthan 302001, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 27.007657,
            longitude: 75.851549,
          },
          departure_time: "09:00",
          arrival_time: "09:30",
          duration: "30 minutes",
          cost: 1000,
          cost_per_person: 500,
          description: "Transfer to Amber Fort.",
        },
        {
          id: "TRN007",
          mode: "Luxury Car",
          from_location: {
            name: "Amber Fort",
            address: "Deonta Amer, Amer, Jaipur, Rajasthan 302001, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 27.007657,
            longitude: 75.851549,
          },
          to_location: {
            name: "Jal Mahal",
            address: "Jal Mahal, Amer, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.953458,
            longitude: 75.846123,
          },
          departure_time: "12:00",
          arrival_time: "12:15",
          duration: "15 minutes",
          cost: 500,
          cost_per_person: 250,
          description: "Transfer to Jal Mahal.",
        },
        {
          id: "TRN008",
          mode: "Luxury Car",
          from_location: {
            name: "Jal Mahal",
            address: "Jal Mahal, Amer, Jaipur, Rajasthan 302002, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.953458,
            longitude: 75.846123,
          },
          to_location: {
            name: "Brewlicious Rooftop Bar Restaurant",
            address:
              "5, 10th floor, Gadi, Okay Plus Tower, Ajmer Rd, near kalyan jewellers, Hathroi, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.917089,
            longitude: 75.799779,
          },
          departure_time: "17:00",
          arrival_time: "17:30",
          duration: "30 minutes",
          cost: 1000,
          cost_per_person: 500,
          description: "Transfer to the rooftop bar.",
        },
        {
          id: "TRN009",
          mode: "Luxury Car",
          from_location: {
            name: "Brewlicious Rooftop Bar Restaurant",
            address:
              "5, 10th floor, Gadi, Okay Plus Tower, Ajmer Rd, near kalyan jewellers, Hathroi, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.917089,
            longitude: 75.799779,
          },
          to_location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          departure_time: "22:00",
          arrival_time: "22:15",
          duration: "15 minutes",
          cost: 500,
          cost_per_person: 250,
          description: "Return to the resort.",
        },
      ],
      daily_cost: 13000,
      weather: {
        date: "2025-10-04",
        min_temp: 23,
        max_temp: 34,
        condition: "Partly Cloudy",
        description: "Warm day with some cloud cover.",
        humidity: 55,
        precipitation: 0,
        recommendation:
          "Continue to wear light clothing. Carry a light jacket for the evening.",
      },
    },
    {
      day_number: 4,
      date: "2025-10-05",
      title: "Wellness, Local Crafts \u0026 Culinary Delights",
      description:
        "Focus on wellness with a yoga session, explore local artisan villages, and indulge in a unique culinary experience.",
      activities: [
        {
          id: "ACT010",
          name: "Morning Yoga and Meditation",
          description:
            "Start your day with a rejuvenating yoga and meditation session at your resort, focusing on peace and wellness.",
          category: "Wellness",
          type: "Yoga",
          location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          start_time: "07:00",
          end_time: "08:30",
          duration: "1.5 hours",
          cost: 2000,
          cost_per_person: 1000,
          booking_required: true,
          rating: 4.7,
          review_count: 400,
          tips: [
            "Book the session in advance with the resort.",
            "Wear comfortable clothing.",
          ],
          priority: 1,
        },
        {
          id: "ACT011",
          name: "Artisan Village Visit (Sanganer or Bagru)",
          description:
            "Visit a nearby artisan village like Sanganer or Bagru, renowned for its traditional block printing and textile crafts. Witness the process and perhaps purchase unique souvenirs.",
          category: "Culture",
          type: "Craft Village",
          location: {
            name: "Sanganer Village",
            address: "Sanganer, Jaipur, Rajasthan 303011, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.835,
            longitude: 75.81,
          },
          start_time: "10:00",
          end_time: "13:00",
          duration: "3 hours",
          cost: 1000,
          cost_per_person: 500,
          booking_required: false,
          rating: 4.2,
          review_count: 700,
          tips: [
            "Arrange for a guided tour to understand the craft better.",
            "Support local artisans by purchasing directly from them.",
          ],
          priority: 2,
        },
        {
          id: "ACT012",
          name: "Culinary Workshop/Experience",
          description:
            "Participate in a hands-on cooking class focusing on Rajasthani vegetarian cuisine, learning to prepare local specialties.",
          category: "Food",
          type: "Cooking Class",
          location: {
            name: "Local Culinary School/Resort",
            address: "Various locations in Jaipur",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912427,
            longitude: 75.787473,
          },
          start_time: "15:00",
          end_time: "17:30",
          duration: "2.5 hours",
          cost: 4000,
          cost_per_person: 2000,
          booking_required: true,
          rating: 4.5,
          review_count: 600,
          tips: [
            "Book this experience in advance.",
            "Choose a class that specializes in vegetarian Rajasthani dishes.",
          ],
          priority: 3,
        },
      ],
      meals: [
        {
          id: "MEAL004",
          type: "Lunch",
          restaurant_name: "Resort Dining",
          description:
            "Enjoy a light and healthy vegetarian lunch at your resort after the artisan village visit.",
          cuisine: "Multi-cuisine, Vegetarian",
          location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          reservation_time: "13:30",
          cost: 1500,
          cost_per_person: 750,
          rating: 4.5,
          review_count: 5000,
          specialties: ["Salads", "Sandwiches", "Light Indian Dishes"],
          dietary_info: ["Vegetarian"],
          booking_required: false,
        },
        {
          id: "MEAL005",
          type: "Dinner",
          restaurant_name: "Culinary Workshop Venue",
          description:
            "Savor the dishes you prepared during the cooking class. This is often included in the workshop cost.",
          cuisine: "Rajasthani, Indian",
          location: {
            name: "Local Culinary School/Resort",
            address: "Various locations in Jaipur",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912427,
            longitude: 75.787473,
          },
          reservation_time: "17:30",
          cost: 0,
          cost_per_person: 0,
          rating: 4.5,
          review_count: 600,
          specialties: ["Dishes prepared during the class"],
          dietary_info: ["Vegetarian"],
          booking_required: true,
        },
      ],
      transport: [
        {
          id: "TRN010",
          mode: "Luxury Car",
          from_location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          to_location: {
            name: "Sanganer Village",
            address: "Sanganer, Jaipur, Rajasthan 303011, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.835,
            longitude: 75.81,
          },
          departure_time: "10:00",
          arrival_time: "10:30",
          duration: "30 minutes",
          cost: 1000,
          cost_per_person: 500,
          description: "Transfer to Sanganer village.",
        },
        {
          id: "TRN011",
          mode: "Luxury Car",
          from_location: {
            name: "Sanganer Village",
            address: "Sanganer, Jaipur, Rajasthan 303011, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.835,
            longitude: 75.81,
          },
          to_location: {
            name: "Culinary School/Resort",
            address: "Various locations in Jaipur",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912427,
            longitude: 75.787473,
          },
          departure_time: "13:00",
          arrival_time: "13:30",
          duration: "30 minutes",
          cost: 1000,
          cost_per_person: 500,
          description: "Transfer to the culinary workshop venue.",
        },
        {
          id: "TRN012",
          mode: "Luxury Car",
          from_location: {
            name: "Culinary School/Resort",
            address: "Various locations in Jaipur",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912427,
            longitude: 75.787473,
          },
          to_location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          departure_time: "17:30",
          arrival_time: "17:45",
          duration: "15 minutes",
          cost: 500,
          cost_per_person: 250,
          description: "Return to the resort.",
        },
      ],
      daily_cost: 10000,
      weather: {
        date: "2025-10-05",
        min_temp: 22,
        max_temp: 33,
        condition: "Sunny",
        description: "Pleasant day, good for outdoor activities and wellness.",
        humidity: 50,
        precipitation: 0,
        recommendation:
          "Light cotton wear. Stay hydrated. Comfortable for yoga.",
      },
    },
    {
      day_number: 5,
      date: "2025-10-06",
      title: "Leisurely Morning \u0026 Departure",
      description:
        "Enjoy a final leisurely breakfast and some last-minute souvenir shopping before departing from Jaipur.",
      activities: [
        {
          id: "ACT013",
          name: "Leisurely Breakfast and Resort Enjoyment",
          description:
            "Savor a relaxed breakfast at your resort and enjoy some final moments of tranquility.",
          category: "Leisure",
          type: "Dining",
          location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          start_time: "08:00",
          end_time: "09:30",
          duration: "1.5 hours",
          cost: 1000,
          cost_per_person: 500,
          booking_required: false,
          rating: 4.5,
          review_count: 5000,
          tips: ["Try local Rajasthani breakfast items if available."],
          priority: 1,
        },
        {
          id: "ACT014",
          name: "Souvenir Shopping",
          description:
            "Pick up some last-minute authentic Rajasthani handicrafts, textiles, or jewelry as souvenirs.",
          category: "Shopping",
          type: "Souvenir Shopping",
          location: {
            name: "Local Market / Resort Boutique",
            address: "Various locations in Jaipur",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912427,
            longitude: 75.787473,
          },
          start_time: "09:30",
          end_time: "11:00",
          duration: "1.5 hours",
          cost: 2000,
          cost_per_person: 1000,
          booking_required: false,
          rating: 4.3,
          review_count: 6000,
          tips: [
            "Consider buying block-printed fabrics, blue pottery, or lacquerware.",
          ],
          priority: 2,
        },
      ],
      meals: [],
      transport: [
        {
          id: "TRN013",
          mode: "Luxury Car",
          from_location: {
            name: "Jai Mahal Palace, Jaipur",
            address:
              "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.912172,
            longitude: 75.785178,
          },
          to_location: {
            name: "Jaipur International Airport",
            address:
              "Affluent Colony, Sanganer, Jaipur, Rajasthan 303011, India",
            city: "Jaipur",
            state: "Rajasthan",
            country: "India",
            latitude: 26.827643,
            longitude: 75.812073,
          },
          departure_time: "11:30",
          arrival_time: "12:30",
          duration: "1 hour",
          cost: 2000,
          cost_per_person: 1000,
          description: "Airport transfer for departure.",
          notes: ["Allow ample time for check-in and security at the airport."],
        },
      ],
      daily_cost: 4000,
      weather: {
        date: "2025-10-06",
        min_temp: 21,
        max_temp: 33,
        condition: "Sunny",
        description: "Clear skies and pleasant weather for departure.",
        humidity: 48,
        precipitation: 0,
        recommendation: "Pack accordingly for your onward journey.",
      },
      notes: [
        "This itinerary is a suggestion and can be customized based on your preferences and pace.",
      ],
    },
  ],
  accommodations: [
    {
      id: "ACC001",
      name: "Jai Mahal Palace, Jaipur",
      type: "Heritage Resort",
      description:
        "A 17th-century palace set amidst 18 acres of Mughal gardens, offering luxurious rooms, fine dining, and a tranquil ambiance.",
      location: {
        name: "Jai Mahal Palace, Jaipur",
        address:
          "Gound Floor, Jacob Rd, near Bharat Petroleum, Civil Lines, Jaipur, Rajasthan 302006, India",
        city: "Jaipur",
        state: "Rajasthan",
        country: "India",
        latitude: 26.912172,
        longitude: 75.785178,
      },
      check_in_date: "2025-10-02",
      check_out_date: "2025-10-06",
      nights: 4,
      room_type: "Luxury Room",
      guests: 2,
      cost_per_night: 8750,
      total_cost: 35000,
      rating: 4.5,
      review_count: 5000,
      amenities: [
        "Swimming Pool",
        "Spa",
        "Fitness Center",
        "Gardens",
        "Multi-cuisine Restaurant",
        "Bar",
      ],
      check_in_time: "14:00",
      check_out_time: "12:00",
      cancellation_info:
        "Standard cancellation policy applies, check at booking.",
    },
    
    
  ],
  generated_at: "2025-09-21T15:15:08.9136526+05:30",
  ai_model: "gemini-2.5-flash-lite",
  language: "en",
  highlight_activities: [
    "Explore the City Palace and Hawa Mahal",
    "Visit the majestic Amber Fort",
    "Experience a Rajasthani folk performance",
    "Participate in a local cooking class",
    "Relax with a yoga session at the resort",
    "Shop for traditional handicrafts",
  ],
  local_insights: [
    "Jaipur is known as the 'Pink City' due to the color of its buildings, painted in honor of a visit by the Prince of Wales in 1876.",
    "Bargaining is an integral part of shopping in local markets; do so respectfully.",
    "Rajasthani cuisine is rich and flavorful, with many vegetarian specialties like Dal Baati Churma and Gatte ki Sabzi.",
    "October marks the beginning of the pleasant tourist season in Rajasthan after the monsoon.",
    "The local language is Hindi, but English is widely understood in tourist areas and hotels.",
  ],
  travel_tips: [
    "Stay hydrated by drinking plenty of bottled water.",
    "Wear comfortable walking shoes.",
    "Carry sunscreen, sunglasses, and a hat to protect yourself from the sun.",
    "Respect local customs and traditions, especially when visiting religious sites.",
    "Keep your belongings secure, especially in crowded places.",
    "Confirm opening hours and entry fees for attractions in advance.",
  ],
  weather_info: {
    season: "Autumn",
    description:
      "October in Jaipur is characterized by pleasant weather, with warm days and cooler evenings. It's an ideal time to visit as the monsoon recedes.",
    avg_min_temp: 20,
    avg_max_temp: 33,
    recommendation:
      "Light cotton clothing is recommended for daytime. A light jacket or shawl might be useful for cooler evenings.",
  },
};
